apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: ghcr-
namespace: demo-ghcr
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newName: ghcr.io/stefanprodan/podinfo
    newTag: c93861a534a6d9adc3e186f6b2d62c73f671a948
patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "#blue"
