apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: local-
namespace: demo-local
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newName: localhost:5001/podinfo
    newTag: dev-ca663c5
patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "#green"
