apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  endpoints:
    - port: http-metrics
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s