# kube-prometheus-stack values for GitOps demo (revised)

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      limits:
        cpu: 2000m
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 512Mi
  
  # 配置 Prometheus 服務為 NodePort
  service:
    type: NodePort
    nodePort: 30090

grafana:
  # 設定固定密碼（僅適用於開發/測試環境）
  adminUser: admin
  adminPassword: admin123
  
  persistence:
    enabled: true
    storageClassName: standard
    size: 10Gi

  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  service:
    type: NodePort
    nodePort: 30301

  # 啟用預設套件儀表板
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: Asia/Taipei

  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

alertmanager:
  enabled: true
  
  # 配置 AlertManager 服務為 NodePort
  service:
    type: NodePort
    nodePort: 30093
  
  # 完整的 AlertManager 配置，包含 Discord 路由
  config:
    global:
      resolve_timeout: 1m
    
    receivers:
    - name: 'null'
    
    - name: 'discord-critical'
      webhook_configs:
      - url: 'http://alertmanager-discord:9094'
        send_resolved: true
        
    - name: 'discord-warning'
      webhook_configs:
      - url: 'http://alertmanager-discord:9094'
        send_resolved: true
        
    - name: 'discord-info'
      webhook_configs:
      - url: 'http://alertmanager-discord:9094'
        send_resolved: true
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 5s
      group_interval: 15s
      repeat_interval: 1m
      receiver: 'null'
      
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
        
      - match:
          severity: critical
        receiver: 'discord-critical'
        group_wait: 5s
        repeat_interval: 1m
        
      - match:
          severity: warning
        receiver: 'discord-warning'
        group_wait: 5s
        repeat_interval: 1m
        
      - match:
          severity: info
        receiver: 'discord-info'
        group_wait: 5s
        repeat_interval: 1m
        
      - match_re:
          service: podinfo.*
        receiver: 'discord-warning'
        group_by: ['alertname', 'pod']
        group_wait: 5s
        repeat_interval: 1m
    
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match_re:
        severity: 'warning|info'
      equal: ['alertname', 'namespace']
      
    - source_match:
        severity: 'warning'
      target_match:
        severity: 'info'
      equal: ['alertname', 'namespace']
  
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 64Mi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
  collectors:
    - certificatesigningrequests
    - configmaps
    - cronjobs
    - daemonsets
    - deployments
    - endpoints
    - horizontalpodautoscalers
    - ingresses
    - jobs
    - leases
    - limitranges
    - mutatingwebhookconfigurations
    - namespaces
    - networkpolicies
    - nodes
    - persistentvolumeclaims
    - persistentvolumes
    - poddisruptionbudgets
    - pods
    - replicasets
    - replicationcontrollers
    - resourcequotas
    - secrets
    - services
    - statefulsets
    - storageclasses
    - validatingwebhookconfigurations
    - volumeattachments

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

additionalServiceMonitors:
  - name: podinfo-monitor
    selector:
      matchLabels:
        app: podinfo
    namespaceSelector:
      any: true
    endpoints:
      - port: http-metrics
        interval: 15s
        path: /metrics
