apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-matrix
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: local
            ns: demo-local
            path: k8s/podinfo/overlays/dev-local
            color: green
          - env: ghcr
            ns: demo-ghcr
            path: k8s/podinfo/overlays/dev-ghcr
            color: blue
  template:
    metadata:
      name: podinfo-{{env}}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/liu-chun-wu/k8s-Gitops-Prometheus-Grafana.git
        path: "{{path}}"
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ns}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
